# Copyright (c) Microsoft Corporation
# SPDX-License-Identifier: MIT

# Main YML file for the CICD pipeline

name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Run on a daily schedule to perform the full set of tests.
  schedule:
    - cron: '00 21 * * *'

permissions:
  id-token: write
  contents: read
  packages: write

concurrency:
  # Cancel any CI/CD workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: cicd-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      matrix:
        configuration: [ 'Release', 'Debug' ]
        platform: [  'windows-2019', 'windows-2022' ] # 'ubuntu-22.04',
        option: [ none ] # , sanitizer, coverage, jit ]
        exclude:
          - platform: windows-2019
            option: sanitizer
          - platform: windows-2019
            option: coverage
          - platform: windows-2022
            option: sanitizer
          - platform: windows-2022
            option: coverage
          - platform: ubuntu-22.04
            option: jit

    uses: ./.github/workflows/Build.yml
    with:
      platform: ${{ matrix.platform }}
      configuration: ${{ matrix.configuration }}
      option: ${{ matrix.option }}

  finish:
    needs:
      - build_and_test
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: Coveralls Finished
      uses: coverallsapp/github-action@95b1a2355bd0e526ad2fd62da9fd386ad4c98474 # v2.2.1
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

